import "normalize.css"
import "./styles/variables.scss"
import "./styles/main.scss"
import "./styles/navBar.scss"
import "./styles/mainScreen.scss"
import "./styles/aboutUs.scss"
import "./styles/workshops.scss"
import "./circleText"
import "./swiperSlider"
import Swiper from "swiper"
